### PR TITLE
fix multipart multi-stream paging by only asking a stream for as much…

### LINKED ISSUE #1119: Large POST requests aborting immediately. #1077 is still an issue.
I am getting the following exception when posting a large (2mb) multipart form.

`WebException: The request was aborted: The request was canceled.`

Same as #1077

### PR DESCRIPTION
**Pull request by baronfel**
… of the requested count as it can provide

Fixes #1119  and #1077 for multipart payloads. Formdata payloads were not impacted, but I added some larger tests anyway.

### CODE REVIEW

File: src/Net/Http.fs [hunk 1]
```diff
@@ -1019,7 +1019,7 @@ module private HttpHelpers =
                 then 0
                 else
                     let stream = Seq.head streams
-                    let read = stream.Read(buffer, offset, max count (int stream.Length))
+                    let read = stream.Read(buffer, offset, min count (int stream.Length))
```
Comment (baronfel) [inline src/Net/Http.fs]: here was the real problem

File: src/Net/Http.fs [hunk 2]
```diff
@@ -1162,11 +1162,15 @@ module private HttpHelpers =
...
-                then alternateFromBeginEnd req.BeginGetRequestStream req.EndGetRequestStream req
-                else Async.FromBeginEnd(req.BeginGetRequestStream, req.EndGetRequestStream)
 
+#if FX_NO_LOCAL_FILESYSTEM
+            use! output =
+              if Type.GetType("Mono.Runtime") <> null
+              then alternateFromBeginEnd req.BeginGetRequestStream req.EndGetRequestStream req
+              else Async.FromBeginEnd(req.BeginGetRequestStream, req.EndGetRequestStream)
+#else
+            use! output = req.GetRequestStreamAsync () |> Async.AwaitTask
```
Comment (baronfel) [inline src/Net/Http.fs]: added this because it's a framework-built in fix that may work better long-term? can go/no-go with it as you please.

File: tests/FSharp.Data.Tests/Http.fs [hunk 3]
```diff
@@ -88,16 +89,25 @@ let ``Setting timeout in customizeHttpRequest overrides timeout argument`` () =
...
     response.StatusCode |> should equal 401
 
-[<Test>]
-let ``4k+ bodies work`` () =
-    let bodyString2 = seq {for i in 0..4000 -> "x\n"} |> String.concat ""
-    let body2 = FSharp.Data.FormValues([("input", bodyString2)])
+let testFormDataSizesInBytes = [
+    4000    // previous test size
+    20000   // previous test size
+    40000   // > 80k, reported by user @danyx23 on full-framework
```
Comment (baronfel) [inline tests/FSharp.Data.Tests/Http.fs]: note that we write two-bytes for each n here, so that's why the numbers are off from the reported numbers. newlines and such.

File: tests/FSharp.Data.Tests/Http.fs [hunk 4]
```diff
@@ -88,16 +89,25 @@ let ``Setting timeout in customizeHttpRequest overrides timeout argument`` () =
...
+    let body = FormValues([("input", bodyString)])
 
-[<Test>]
-let ``32k+ bodies work`` () =
-    let bodyString2 = seq {for i in 0..20000 -> "x\n"} |> String.concat ""
-    let body2 = FSharp.Data.FormValues([("input", bodyString2)])
+    Assert.DoesNotThrow(fun () -> Http.Request (url="http://httpbin.org/post", httpMethod="POST", body=body) |> ignore)
+
+[<Test; TestCaseSource("testFormDataSizesInBytes")>]
+let testMultipartFormDataBodySize (size: int) =
```
Comment (baronfel) [inline tests/FSharp.Data.Tests/Http.fs]: yay multipart coverage, something I should have done originally!

**Comment by ovatsus** [comment]
Looks good, can you also update the release notes?

**Comment by baronfel** [comment]
Absolutely.

**Comment by ovatsus** [comment]
Oops, merged a bit too soon, one of the new tests is failing (and I can also repro locally)

        1) Failed : FSharp.Data.Tests.Http.testFormDataBodySize(20000)
          Expected: No Exception to be thrown
          But was:  <System.Net.WebException: The remote server returned an error: (408) Request Timeout.
        Response from http://httpbin.org/post:
        <html><head><title>Request Timeout</title></head><body><p>Request Timeout.</p></body></html> ---> System.Net.WebException: The remote server returned an error: (408) Request Timeout.
           at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
           at <StartupCode$FSharp-Core>.$Control.callback@1712.Invoke(IAsyncResult ar)
           --- End of inner exception stack trace ---
           at Microsoft.FSharp.Control.AsyncBuilderImpl.commit[a](Result`1 res)
           at Microsoft.FSharp.Control.CancellationTokenOps.RunSynchronously[a](CancellationToken token, FSharpAsync`1 computation, FSharpOption`1 timeout)
           at Microsoft.FSharp.Control.FSharpAsync.RunSynchronously[T](FSharpAsync`1 computation, FSharpOption`1 timeout, FSharpOption`1 cancellationToken)
           at FSharp.Data.Tests.Http.testFormDataBodySize@105.Invoke() in C:\projects\fsharp-data\tests\FSharp.Data.Tests\Http.fs:line 105
           at NUnit.Framework.Constraints.ThrowsConstraint.VoidInvocationDescriptor.Invoke()
           at NUnit.Framework.Constraints.ThrowsConstraint.ExceptionInterceptor.Intercept(Object invocation)>
        at FSharp.Data.Tests.Http.testFormDataBodySize(Int32 size) in C:\projects\fsharp-data\tests\FSharp.Data.Tests\Http.fs:line 105

**Comment by ovatsus** [comment]
It's only a test issue, so I've released 2.4.5 with the fix anyway
