### PR TITLE
Fix form body url encoding #1104

### LINKED ISSUE #1104: Large post body causes erroneous 'Invalid URI: The Uri string is too long.' error
Hey again, 

A while back I posted an issue #1077 which found that `FSharp.Data.Http.Request` would fail if the body size was too large.

This issue is to report that again the same thing is happening but now for larger body values. The biggest problem is that the error message produced is incorrect as well. When a large body is passed in the error given is `'Invalid URI: The Uri string is too long.'` when I can demonstrate that running with the same URI and just changing the body causes the failure.

This is the same example code I posted in issue #1077 except increased the size of the second test case:
```
#r @"FSharp.Data.dll"
open FSharp.Data

let bodyString = seq {for i in 0..1000 -> "x\n"} |> String.concat ""
let body = FSharp.Data.FormValues([("input",bodyString)])
FSharp.Data.Http.Request(url="http://httpbin.org/post",httpMethod="POST",body=body)
//Works fine

let bodyString2 = seq {for i in 0..20000 -> "x\n"} |> String.concat ""
let body2 = FSharp.Data.FormValues([("input",bodyString2)])
FSharp.Data.Http.Request(url="http://httpbin.org/post",httpMethod="POST",body=body2)
//throws System.UriFormatException: Invalid URI: The Uri string is too long.
```

As you can see the URI should be the same in both cases.

### PR DESCRIPTION
**Pull request by panesofglass**
This patch is intended to fix #1104. `Uri.EscapeDataString` fails to handle more than 32k characters, but `application/x-www-form-urlencoded` has no such restriction. While `WebUtility.UrlEncode` is [not quite sufficient](https://blogs.msdn.microsoft.com/yangxind/2006/11/08/dont-use-net-system-uri-unescapedatastring-in-url-decoding/) for correct encoding, a simple `Replace` fix can make it work.

### CODE REVIEW

**Comment by panesofglass** [comment]
cc @baronfel

**Comment by baronfel** [comment]
@ovatsus I worked through this fix with @panesofglass and think it's the way to go.  Seeing some design-time failures in CI that aren't related at all though.

**Comment by ovatsus** [comment]
Does this also fix #1082?

**Comment by ovatsus** [comment]
The new test is failing on AppVeyor


    1) Failed : FSharp.Data.Tests.Http.32k+ bodies work
      Expected: No Exception to be thrown
      But was:  <System.Net.WebException: The remote server returned an error: (408) Request Timeout.
    Response from http://httpbin.org/post:
    <html><head><title>Request Timeout</title></head><body><p>Request Timeout.</p></body></html> ---> System.Net.WebException: The remote server returned an error: (408) Request Timeout.
       at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
       at <StartupCode$FSharp-Core>.$Control.callback@1712.Invoke(IAsyncResult ar)
       --- End of inner exception stack trace ---
       at Microsoft.FSharp.Control.AsyncBuilderImpl.commit[a](Result`1 res)
       at Microsoft.FSharp.Control.CancellationTokenOps.RunSynchronously[a](CancellationToken token, FSharpAsync`1 computation, FSharpOption`1 timeout)
       at Microsoft.FSharp.Control.FSharpAsync.RunSynchronously[T](FSharpAsync`1 computation, FSharpOption`1 timeout, FSharpOption`1 cancellationToken)
       at FSharp.Data.Tests.Http.32k- bodies work@103.Invoke() in C:\projects\fsharp-data\tests\FSharp.Data.Tests\Http.fs:line 103
       at NUnit.Framework.Constraints.ThrowsConstraint.VoidInvocationDescriptor.Invoke()
       at NUnit.Framework.Constraints.ThrowsConstraint.ExceptionInterceptor.Intercept(Object invocation)>
    at FSharp.Data.Tests.Http.32k+ bodies work() in C:\projects\fsharp-data\tests\FSharp.Data.Tests\Http.fs:line 103
    Run Settings
        DisposeRunners: True

File: src/Net/Http.fs [hunk 1]
```diff
@@ -1513,6 +1513,12 @@ type Http private() =
 #endif
 
     static let charsetRegex = Regex("charset=([^;\s]*)", regexOptions)
+    
+    /// Correctly encodes large form data values.
+    /// See https://blogs.msdn.microsoft.com/yangxind/2006/11/08/dont-use-net-system-uri-unescapedatastring-in-url-decoding/
+    /// and https://msdn.microsoft.com/en-us/library/system.uri.escapedatastring(v=vs.110).aspx
+    static member internal UrlEncode (query:string) =
+        (WebUtility.UrlEncode query).Replace("+","%20")
```
Comment (ovatsus) [inline src/Net/Http.fs]: Is WebUtility.UrlEncode available on PCL 7 and PCL 259?

Comment (panesofglass) [reply src/Net/Http.fs]: [`WebUtility` is available in `Profile7`](https://stackoverflow.com/a/28974461). It's available when targeting .NET 4.5. What is FSharp.Data targeting? Also, do you use `System.Web.HttpUtility` anwhere? I assume not if you are targeting PCL.

**Comment by panesofglass** [comment]
I don't _think_ this is related to #1082 since that is uploading a file, not `application/x-www-form-urlencoded`.

**Comment by panesofglass** [comment]
Based on NuGet.org, it seems the minimum target is .NET 4.0. Is there a definition for NET40 separate from NET45+? If so, I could use `System.Web.HttpUtility` for NET40 and `System.Net.WebUtility` for all others. Also, I saw there was [another encoding borrowed from Mono](https://github.com/fsharp/FSharp.Data/blob/1f67e15351b542b6c022d49881bcef3b3a02499e/src/Json/JsonValue.fs#L98) that you could probably do the same.

**Comment by ovatsus** [comment]
We used to support .NET 4.0 and other PCL profiles, but now we only support .NET 4.5+ and PCL 7 and 259, so we just need something that's available on those 3. Maybe that code copied from Mono in JsonValue is not needed anymore

**Comment by panesofglass** [comment]
Thanks, @ovatsus and @baronfel!
